# FILE VERSION DO NOT TOUCH!
file-version: 1
# Main Config for the Manhunt plugin developed by davy.
# Please for support contact me on GitHub Issues (for now)
# FUTURE PLANS:
# GUI Editor (Enable the chance to completely modify the gui as you want)
# ??? (If you have an idea open a GitHub issue!)

# AUTO UPDATER
auto-update: false

# Runners
runners: []

# Scoreboards
waiting-scoreboard:
  title: "&4Manhunt - WAITING"
  lines: []

game-scoreboard:
  title: "&4Manhunt - BY DAVIDEENOO"
  lines: []

spectator-scoreboard:
  title: "&4Manhunt - Spectator"
  lines: []

# LOBBY, AS I STILL DON'T KNOW A BETTER METHOD (IF YOU KNOW PLEASE TELL ME)
# FOR NOT HAVING PROBLEMS WITH SCOREBOARD SET THIS TO YOUR LOBBY-NAME (CASE SENSITIVE)
lobby-world: "world"

# Main Configuration part
min-required-players: 2 # Max 10 (for now)
max-required-players: 10 # Max 100 (for now)
min-required-hunters: 1 # Max 10 (for now)
min-required-runners: 1 # Max 10 (for now)
runners-headstart: 20 # Max 1m (for now)
countdown: 30 # Max 1m (for now)

# Random Events
dolphin-event:
  duration:
  repeat-delay:

# Custom Tablist
custom-tablist:
  enabled: false

